/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LISTA_H_RPCGEN
#define _LISTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct no {
	int dado;
	struct no *next;
};
typedef struct no no;

#define LISTAPROG 0x20000199
#define LISTAVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define init 1
extern  int * init_1(int *, CLIENT *);
extern  int * init_1_svc(int *, struct svc_req *);
#define insere 2
extern  int * insere_1(int *, CLIENT *);
extern  int * insere_1_svc(int *, struct svc_req *);
#define deleta 3
extern  int * deleta_1(int *, CLIENT *);
extern  int * deleta_1_svc(int *, struct svc_req *);
#define consulta 4
extern  int * consulta_1(int *, CLIENT *);
extern  int * consulta_1_svc(int *, struct svc_req *);
#define imprima 5
extern  int * imprima_1(int *, CLIENT *);
extern  int * imprima_1_svc(int *, struct svc_req *);
extern int listaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init 1
extern  int * init_1();
extern  int * init_1_svc();
#define insere 2
extern  int * insere_1();
extern  int * insere_1_svc();
#define deleta 3
extern  int * deleta_1();
extern  int * deleta_1_svc();
#define consulta 4
extern  int * consulta_1();
extern  int * consulta_1_svc();
#define imprima 5
extern  int * imprima_1();
extern  int * imprima_1_svc();
extern int listaprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_no (XDR *, no*);

#else /* K&R C */
extern bool_t xdr_no ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LISTA_H_RPCGEN */
